import { ArrowDownRight, BadgeCheck, BriefcaseBusiness, Building2, Landmark, Scale } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import SiteFooter from "../../../components/SiteFooter";
import SiteHeader from "../../../components/SiteHeader";
import { heroTitleClass } from "../../../lib/hero-title";

const practiceAreas = {
  "private-limited-company": {
    eyebrow: "Company incorporation", title: "Private limited companies", image: "/images/sattva/practice-areas/corporate-commercial-law.jpg", imageAlt: "Professionals discussing a business structure",
    focusTitle: "A clear start for", focusEmphasis: "a growing company.", workflow: ["Choose the shareholding and management structure", "Prepare incorporation documents and filings", "Set up the first compliance calendar"],
    lead: "Practical support to incorporate a private limited company and put its first essential compliance steps in place.",
    body: ["A private limited company can be a strong foundation for a business that is planning to build a team, bring in investors or establish a defined ownership structure. We help make the formation process easier to follow from the first decision through incorporation.", "Our support brings the key documents, filings and initial statutory actions into one clear sequence, so the company begins with its records and responsibilities in good order."],
    scope: ["Company name and structure guidance", "Incorporation documentation and filing support", "Director, shareholder and registered-office coordination", "Initial statutory records and compliance roadmap"],
  },
  "limited-liability-partnership": {
    eyebrow: "Company incorporation", title: "Limited liability partnerships", image: "/images/sattva/practice-areas/commercial-contracts.jpg", imageAlt: "People reviewing partnership documents",
    focusTitle: "A practical structure", focusEmphasis: "for working together.", workflow: ["Clarify partner roles and contributions", "Prepare the LLP incorporation materials", "Put the LLP agreement and filings in order"],
    lead: "Structured support for establishing an LLP with clear partner arrangements and a dependable compliance base.",
    body: ["An LLP can offer a flexible framework for partners who want to run a business together while defining rights, duties and decision-making from the outset. We help clients work through the core setup decisions in a practical order.", "From incorporation through the LLP agreement and initial filings, we focus on creating clear documentation that supports the way the partners intend to work together."],
    scope: ["Partner and contribution structure guidance", "LLP name reservation and incorporation support", "LLP agreement preparation and filing", "Initial records and compliance roadmap"],
  },
  "one-person-company": {
    eyebrow: "Company incorporation", title: "One person companies", image: "/images/sattva/practice-areas/startup-growth.jpg", imageAlt: "Founder working with a business plan",
    focusTitle: "A company structure", focusEmphasis: "for an independent founder.", workflow: ["Confirm the proposed company structure", "Prepare incorporation and nominee details", "Set out the first compliance actions"],
    lead: "Clear incorporation support for founders setting up a one person company and its essential records.",
    body: ["A one person company can give an individual founder a formal company structure while keeping the setup focused. We help identify the key incorporation inputs and organise the documents needed to proceed.", "The aim is to make the path from an initial idea to a properly established company easier to understand, with the required records and ongoing responsibilities visible from the beginning."],
    scope: ["OPC structure and nominee guidance", "Incorporation documentation and filing support", "Director and registered-office coordination", "Initial statutory records and compliance roadmap"],
  },
  "section-8-company": {
    eyebrow: "Company incorporation", title: "Section 8 companies", image: "/images/sattva/practice-areas/corporate-governance.jpg", imageAlt: "Team gathered around a meeting table",
    focusTitle: "A purpose-led structure", focusEmphasis: "for not-for-profit work.", workflow: ["Clarify the charitable or social purpose", "Prepare the incorporation and licence application", "Set out the first governance and compliance actions"],
    lead: "Focused support for incorporating a Section 8 company with a clear purpose, governance structure and record-keeping foundation.",
    body: ["A Section 8 company is designed for organisations that want to pursue charitable or other not-for-profit objects through a company structure. The purpose, proposed activities and governance arrangements need to be clear from the start.", "We help bring the incorporation documents, application materials and early governance records into a practical sequence, so the organisation begins with a dependable structure for its work."],
    scope: ["Purpose and object-clause guidance", "Section 8 incorporation and licence application support", "Member, director and governance documentation", "Initial statutory records and compliance roadmap"],
  },
  "foreign-subsidiary": {
    eyebrow: "Company incorporation", title: "Foreign subsidiaries", image: "/images/sattva/practice-areas/fema-filings.jpg", imageAlt: "International business documents and port infrastructure",
    focusTitle: "An Indian base for", focusEmphasis: "cross-border growth.", workflow: ["Review the proposed ownership and activity", "Prepare the incorporation and investment documents", "Plan the first company and foreign-investment actions"],
    lead: "Structured support for establishing an Indian subsidiary, with the incorporation, ownership and reporting steps considered together.",
    body: ["A foreign subsidiary needs its Indian company structure, intended activity and ownership arrangements to work together from the outset. The relevant route and documentation depend on the proposed investment and business plan.", "We coordinate the incorporation materials with the practical company-law and foreign-investment steps that follow, giving the parent company a clearer view of the records, approvals and reporting points involved."],
    scope: ["Indian subsidiary structure and incorporation guidance", "Foreign ownership and investment-document coordination", "Company-law and foreign-investment reporting support", "Initial governance and compliance roadmap"],
  },
  "corporate-commercial-law": {
    eyebrow: "Corporate & commercial law", title: "Corporate & commercial law", image: "/images/sattva/practice-areas/corporate-commercial-law.jpg", imageAlt: "Colleagues in a business meeting",
    focusTitle: "A framework for", focusEmphasis: "business decisions.", workflow: ["Clarify the business structure", "Set out the commercial terms", "Coordinate the next actions"],
    lead: "Practical legal support for the decisions, structures and commercial relationships that sit behind a growing business.",
    body: ["Businesses need legal advice that understands both the immediate decision and the wider direction of travel. We support companies through the foundational corporate work that gives everyday operations a dependable base.", "From structuring a new venture to documenting a new relationship, we help keep the legal position clear, proportionate and connected to the commercial outcome you are working towards."],
    scope: ["Business structure and incorporation support", "Commercial arrangements and governance questions", "Routine corporate documentation", "Support through change, growth and new transactions"],
  },
  "corporate-governance-secretarial-matters": {
    eyebrow: "Corporate governance", title: "Corporate governance & secretarial matters", image: "/images/sattva/practice-areas/corporate-governance.jpg", imageAlt: "Team gathered around a meeting table",
    focusTitle: "Governance that keeps", focusEmphasis: "the work in order.", workflow: ["Map the relevant obligations", "Prepare records and resolutions", "Support the meeting cycle"],
    lead: "A dependable framework for the records, meetings and obligations that support responsible company administration.",
    body: ["Good governance is not just about meeting a deadline. It is a working record of how a company makes decisions, keeps its commitments visible and maintains confidence with its stakeholders.", "We help bring order to the recurring and event-based work behind company administration, so that records, resolutions and filings are ready when they are needed."],
    scope: ["Annual and event-based company filings", "Board and shareholder meeting support", "Statutory registers and corporate records", "Company secretarial documentation"],
  },
  "commercial-contracts-documentation": {
    eyebrow: "Commercial contracts", title: "Commercial contracts & documentation", image: "/images/sattva/practice-areas/commercial-contracts.jpg", imageAlt: "Person signing a business document",
    focusTitle: "Terms that work", focusEmphasis: "in practice.", workflow: ["Understand the arrangement", "Draft and review the terms", "Support a clear execution"],
    lead: "Clear documentation that helps each party understand the terms of a working relationship from the outset.",
    body: ["An agreement should give everyone involved a clear and workable understanding of the arrangement. We begin with the commercial intent, then shape the legal terms around the way the relationship will actually operate.", "Whether the document is for a new venture, customer engagement, supplier relationship or internal appointment, we focus on precision without losing sight of the practical next step."],
    scope: ["Founder, shareholder and partnership agreements", "Vendor, customer and service agreements", "Employment and consultancy documentation", "Non-disclosure, lease and commercial arrangements"],
  },
  "sebi-regulatory-practice": {
    eyebrow: "SEBI regulatory practice", title: "SEBI regulatory practice", image: "/images/sattva/practice-areas/sebi-regulatory.jpg", imageAlt: "Financial market data displayed on a screen",
    focusTitle: "Careful process for", focusEmphasis: "regulated work.", workflow: ["Assess the registration route", "Build the required documentation", "Prepare the compliance rhythm"],
    lead: "Focused support for regulated professionals navigating registration, operating requirements and ongoing compliance.",
    body: ["Regulated work depends on well-prepared documentation and a process that can be maintained after approval. We help clients make sense of the administrative requirements that sit alongside a research or advisory practice.", "Our role is to bring structure to the registration and readiness work, with a clear view of the records, disclosures and operating practices that need attention."],
    scope: ["Research analyst registration", "Investment adviser registration", "Compliance process and documentation setup", "Audit-readiness support for regulated practices"],
  },
  "research-analyst-registration": {
    eyebrow: "RA / IA compliance", title: "Research analyst registration", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=85", imageAlt: "Financial analysis dashboard on a computer screen",
    focusTitle: "A clear route into", focusEmphasis: "regulated research.", workflow: ["Map the proposed research activity", "Review readiness and supporting information", "Prepare the application and operating materials", "Set up the first compliance rhythm"],
    lead: "Structured support for applicants establishing a research-analyst practice, from early readiness review through registration materials and the compliance framework that follows.",
    body: ["The work begins by understanding what will be published or communicated, who will be responsible for research activity and how the practice is intended to operate. That early map helps distinguish the proposed activity and identify the records, disclosures and processes that need attention before an application is prepared.", "We then organise the application information and supporting materials into a practical workstream. The focus is on accuracy, consistency and a clear evidence trail—not on producing a generic filing pack detached from the way the business will work.", "After the registration stage, we help translate the framework into day-to-day controls around research reports, disclosures, communications, grievance handling and record retention. The precise requirements depend on the applicant and activity, so each setup is reviewed on its own facts."],
    scope: ["Registration-readiness and activity review", "Application information and document coordination", "Research-report, disclosure and communication framework", "Client grievance and record-management process", "Ongoing compliance-calendar guidance"],
    engagement: { start: ["A confidential readiness discussion focused on the intended research activity, applicant structure and practical launch plan.", "A document and responsibility map showing the information, approvals and internal owners needed for the next stage."], delivery: ["A coordinated application workstream with clear drafts, supporting-document requests and review points.", "A proportionate operating pack covering the policies, disclosures, registers and review routines relevant to the proposed practice."] },
  },
  "investment-adviser-registration": {
    eyebrow: "RA / IA compliance", title: "Investment adviser registration", image: "https://images.unsplash.com/photo-1707157284454-553ef0a4ed0d?auto=format&fit=crop&w=1600&q=85", imageAlt: "Financial reports and charts on a desk",
    focusTitle: "Advice built around", focusEmphasis: "client suitability.", workflow: ["Define the proposed advisory model", "Review registration readiness and controls", "Prepare application and client-facing materials", "Establish the first compliance calendar"],
    lead: "Practical support for launching an investment-advisory practice with a considered registration approach, client-onboarding framework and ongoing compliance foundation.",
    body: ["An investment-advisory engagement starts with the proposed advisory model: who the clients will be, how advice will be delivered, what services sit alongside it and how conflicts will be identified and managed. This gives the registration work a more reliable foundation than treating the application as a stand-alone form-filling exercise.", "We help organise the relevant application inputs, entity and personnel information, policies and client-facing documents in a clear sequence. Each document is reviewed for how it will be used in the intended operating model, including the points where approvals and records need to be maintained.", "Once the practice is ready to operate, the focus shifts to a workable client journey: onboarding, risk profiling, suitability, disclosures, agreements, records and periodic review. The final setup is tailored to the applicant's actual services and current regulatory requirements."],
    scope: ["Advisory-model and registration-readiness review", "Application and supporting-document coordination", "Client onboarding, risk-profiling and suitability framework", "Disclosure, conflict-management and record-keeping process", "Ongoing compliance and audit-readiness guidance"],
    engagement: { start: ["A focused scoping discussion that maps the target client group, advice process, delivery model and existing operating arrangements.", "A readiness checklist that separates immediate application inputs from the systems and records needed for launch."], delivery: ["A sequenced registration workstream with document reviews, clear responsibilities and practical next actions.", "A client-service and compliance foundation designed around onboarding, suitability, disclosures, records and periodic internal review."] },
  },
  "investment-advisory-research-regulation": {
    eyebrow: "IA / RA registration", title: "Investment Adviser & Research Analyst registration", image: "/images/sattva/practice-areas/investment-advisory.jpg", imageAlt: "Professionals discussing work in an office",
    focusTitle: "Structure for a", focusEmphasis: "regulated practice.", workflow: ["Clarify the regulated activity", "Prepare application materials", "Set up working processes"],
    lead: "Considered support for Investment Adviser and Research Analyst registration, compliance setup and ongoing regulatory readiness.",
    body: ["The early design of an investment advisory or research practice can make ongoing compliance more manageable. We help clients identify the relevant regulatory activity and organise the materials needed to move forward with confidence.", "Alongside the application work, we focus on the practical documentation and disclosure processes that help a growing practice operate with care and consistency."],
    scope: ["IA and RA registration application preparation", "One-time compliance setup", "Documentation and disclosure support", "Ongoing regulatory-readiness guidance"],
  },
  "fema-fcgpr-fctrs-filings": {
    eyebrow: "FEMA reporting", title: "FEMA, FCGPR & FCTRS filings", image: "/images/sattva/practice-areas/fema-filings.jpg", imageAlt: "Cargo port handling international shipments",
    focusTitle: "Reporting handled", focusEmphasis: "with clarity.", workflow: ["Map the reporting event", "Coordinate supporting documents", "Submit and track the filing"],
    lead: "Structured support for foreign investment reporting and the filings that accompany cross-border corporate activity.",
    body: ["Cross-border transactions often involve several moving parts: the underlying event, supporting corporate documents, bank coordination and a reporting timeline. We help bring these inputs together in a clear sequence.", "The aim is to make the reporting process more manageable, keeping the documentation, submission and follow-up work organised around the specific transaction."],
    scope: ["FCGPR filing support", "FCTRS filing support", "Documentation coordination with AD banks", "FEMA reporting process guidance"],
  },
  "startup-funding-growth-advisory": {
    eyebrow: "Startup, funding & growth", title: "Startup, funding & growth advisory", image: "/images/sattva/practice-areas/startup-growth.jpg", imageAlt: "Startup team collaborating around a table",
    focusTitle: "A sound base for", focusEmphasis: "the next stage.", workflow: ["Understand the stage and plan", "Prepare the core documents", "Support the next raise or step"],
    lead: "Legal support for founders navigating formation, funding conversations and the documentation that comes with growth.",
    body: ["Growth brings a new set of legal decisions into view: how the company is structured, what is agreed between founders, and how a funding conversation is documented. We help founders deal with those questions in a practical order.", "By connecting formation, governance and funding-readiness work, we give teams a more dependable base for the next raise, milestone or commercial relationship."],
    scope: ["Founder and early-stage structuring guidance", "Funding-readiness documentation", "Startup registrations and operational setup", "Company conversion and growth-stage secretarial work"],
  },
} as const;

const complianceGuides: Record<string, { intro: string; items: { title: string; copy: string }[] }> = {
  "private-limited-company": { intro: "After incorporation, compliance is a continuing cycle of records, approvals and filings. The right actions depend on the company's activity and changes during the year.", items: [{ title: "Set the records in place", copy: "Keep statutory registers, share records, board decisions and the registered-office records current from the start." }, { title: "Run the annual cycle", copy: "Plan financial statements, the audit, annual general meeting and the related MCA filings as one connected annual process." }, { title: "Act when the company changes", copy: "Director, address, share-capital and governance changes can trigger separate filings and should be reviewed before they take effect." }] },
  "limited-liability-partnership": { intro: "An LLP combines the flexibility of a partnership with formal filing and record-keeping responsibilities. The LLP agreement remains central to how the partners operate.", items: [{ title: "Maintain the LLP agreement", copy: "Keep the agreement, partner contributions and profit-sharing terms aligned with the way the LLP actually works." }, { title: "Plan annual LLP filings", copy: "The annual return and statement of account and solvency should be prepared from complete financial and partner records." }, { title: "Record partner changes", copy: "Admissions, resignations, contribution changes and registered-office changes need timely documentation and may require filing updates." }] },
  "one-person-company": { intro: "An OPC is still a company: its individual ownership does not remove the need for proper corporate records and recurring statutory work.", items: [{ title: "Keep company decisions recorded", copy: "Maintain director decisions, nominee details and statutory registers in a clear, accessible record." }, { title: "Follow the annual company cycle", copy: "Financial statements, audit requirements and annual company filings should be planned around the applicable financial year." }, { title: "Review growth events early", copy: "A change in ownership, capital or operating plans may require governance updates or a review of the structure." }] },
  "section-8-company": { intro: "Section 8 compliance is tied closely to the organisation's stated objects, governance records and continuing company-law responsibilities.", items: [{ title: "Keep purpose and governance aligned", copy: "Maintain decisions, records and activities in a way that supports the company's stated objects and governance arrangements." }, { title: "Run the annual company cycle", copy: "Financial statements, audit, annual return and other applicable company filings should be planned as one connected process." }, { title: "Review material changes early", copy: "Changes to the objects, management, registered office or operating plans should be considered before they are implemented." }] },
  "foreign-subsidiary": { intro: "An Indian subsidiary with foreign ownership needs its company records, investment position and recurring filing responsibilities to stay visible together.", items: [{ title: "Maintain ownership and company records", copy: "Keep the statutory registers, share records, board decisions and supporting investment documents current from the outset." }, { title: "Plan recurring company and investment reporting", copy: "Annual company filings and applicable foreign-investment reporting should be organised around reliable records and clear due dates." }, { title: "Review changes before they take effect", copy: "Changes in ownership, capital, directors, address or activity can require separate company-law or foreign-investment actions." }] },
  "corporate-commercial-law": { intro: "Corporate work stays reliable when commercial decisions, approvals and documents are treated as one record rather than separate tasks.", items: [{ title: "Confirm authority", copy: "Check the appropriate internal approval before a material arrangement is signed or implemented." }, { title: "Document the arrangement", copy: "Keep signed agreements, resolutions and key correspondence together so the commercial position can be followed later." }, { title: "Review changes", copy: "New funding, ownership, governance or operating changes may need separate company-law and contractual steps." }] },
  "corporate-governance-secretarial-matters": { intro: "Governance compliance is the discipline of keeping decisions, registers and filings current throughout the year.", items: [{ title: "Keep meeting records complete", copy: "Board and shareholder decisions should be properly convened, recorded and stored with the supporting papers." }, { title: "Maintain statutory registers", copy: "Registers and company records should reflect the current directors, members, charges and other relevant particulars." }, { title: "Track annual and event-based work", copy: "The annual cycle sits alongside filings triggered by changes to the company, its officers or its structure." }] },
  "commercial-contracts-documentation": { intro: "Contract compliance is operational: the signed document should remain usable, visible and connected to the way the relationship is managed.", items: [{ title: "Control the final version", copy: "Keep signed copies, amendments and approval records in one place with the correct parties and dates." }, { title: "Track the key obligations", copy: "Payment, delivery, confidentiality, renewal and notice provisions should be visible to the teams responsible for them." }, { title: "Review before the relationship changes", copy: "A new scope, extension or assignment may need a documented variation rather than an informal update." }] },
  "sebi-regulatory-practice": { intro: "Registration is the beginning of the compliance framework. The operating model, disclosures and review processes need to be maintained after approval.", items: [{ title: "Operate within the registered activity", copy: "Client-facing activity, communications and documents should match the registered role and applicable SEBI framework." }, { title: "Maintain disclosures and records", copy: "The required policies, client materials, disclosures and supporting records should be kept current as the practice develops." }, { title: "Plan periodic review", copy: "Compliance review and audit requirements should be diarised and tested against the current regulatory requirements." }] },
  "research-analyst-registration": { intro: "A research-analyst practice needs its research activity, public communications, disclosures and internal recordkeeping to remain aligned after registration.", items: [{ title: "Keep research records complete", copy: "Maintain the research reports, supporting rationale, disclosures and approval trail in a form that can be located and reviewed." }, { title: "Review public communications", copy: "Website, social-media and client-facing material should be checked against the registered activity and applicable disclosure requirements." }, { title: "Maintain the review rhythm", copy: "Keep grievance handling, policy reviews, records and audit-readiness tasks visible through a practical compliance calendar." }] },
  "investment-adviser-registration": { intro: "An investment-advisory practice is sustained through a client process that keeps advice, suitability, disclosures and records connected to the way the service is delivered.", items: [{ title: "Keep the client journey consistent", copy: "Onboarding, risk profiling, suitability, advisory agreements and advice records should work together as one repeatable client process." }, { title: "Manage disclosures and conflicts", copy: "Review client-facing disclosures and the process for identifying and addressing conflicts as the practice and services develop." }, { title: "Plan regular compliance review", copy: "Maintain a calendar for periodic controls, records, required reviews and audit-readiness work appropriate to the operating model." }] },
  "investment-advisory-research-regulation": { intro: "IA and RA compliance depends on keeping the regulated activity, client communication and internal controls consistent with the applicable SEBI framework.", items: [{ title: "Keep activities appropriately separated", copy: "Where both IA and RA activities are undertaken, the applicable requirements and records must be handled separately, with the required segregation." }, { title: "Use clear disclosures and records", copy: "Research and advisory materials should be supported by the necessary records, disclosures and client-facing documentation." }, { title: "Maintain the review cycle", copy: "Annual compliance audit and other current regulatory obligations should be planned against the applicable IA or RA requirements." }] },
  "fema-fcgpr-fctrs-filings": { intro: "FEMA reporting follows the underlying transaction. The corporate documents, valuation or banking inputs and reporting route need to be coordinated before the filing stage.", items: [{ title: "Start with the transaction documents", copy: "Identify the investment or transfer event, parties, approvals and supporting corporate records before approaching the filing." }, { title: "Coordinate with the authorised dealer bank", copy: "Bank requirements and portal submissions should be checked early, as supporting information can differ by transaction." }, { title: "Keep annual reporting visible", copy: "An Indian company that has received foreign investment may need to consider the annual FLA return; the reporting position should be reviewed each year." }] },
  "startup-funding-growth-advisory": { intro: "Growth-stage compliance links the commercial event to the records, approvals and follow-up actions needed to keep the company in order.", items: [{ title: "Prepare before the transaction", copy: "Ownership records, approvals and core documents should be ready before a funding or structural discussion is finalised." }, { title: "Document the decision clearly", copy: "Term sheets, investment documents, board approvals and shareholder actions should tell one consistent story." }, { title: "Complete the follow-through", copy: "After closing, update statutory records and review whether company-law, FEMA or contractual filings and actions are required." }] },
};

type IncorporationGuide = { intro: string; sections: { title: string; copy: string; bullets: string[] }[] };

const detailIcons = [Building2, Landmark, BadgeCheck, Scale, BriefcaseBusiness];

const incorporationGuides: Record<string, IncorporationGuide> = {
  "private-limited-company": { intro: "A private limited company is best set up as a series of connected decisions, not merely an incorporation filing. The ownership, management and records created at the outset should support the business you intend to build.", sections: [
    { title: "Design the company architecture", copy: "Before documents are prepared, we turn the commercial plan into a workable company structure.", bullets: ["Identify proposed shareholders, directors and decision-makers", "Discuss shareholding, initial capital and control arrangements", "Consider the objects, registered office and early business activity"] },
    { title: "Prepare a consistent filing pack", copy: "The name, constitutional documents and supporting information should tell the same story.", bullets: ["Coordinate identity, address and consent information", "Prepare the memorandum and articles around the intended business", "Review name options and registered-office inputs"] },
    { title: "Move through incorporation in sequence", copy: "We keep the filing work and any clarifications organised around clear next actions.", bullets: ["Confirm incorporation inputs before submission", "Coordinate responses or clarifications if required", "Organise the certificate and foundational corporate records"] },
    { title: "Build the first operating file", copy: "Corporate housekeeping should begin before the first material transaction or funding discussion.", bullets: ["Set up statutory registers, share records and board documentation", "Identify immediate banking, tax, licence and operational registrations", "Create an initial calendar for decisions, filings and record reviews"] },
  ] },
  "limited-liability-partnership": { intro: "An LLP works best when the partners have a shared understanding of capital, authority and decision-making. That understanding belongs in the setup work, not only in later discussions.", sections: [
    { title: "Set out the partner arrangement", copy: "The first step is to make the commercial relationship between the partners visible.", bullets: ["Identify partners, designated partners and decision-making roles", "Discuss contributions, profit sharing and day-to-day responsibilities", "Consider joining, exit and disagreement scenarios"] },
    { title: "Shape the LLP agreement", copy: "The agreement is the LLP's operating manual and should reflect how the partners expect to work.", bullets: ["Address authority, approvals, drawings and remuneration", "Record confidentiality, intellectual-property and client expectations where relevant", "Include practical processes for records, disputes and changes"] },
    { title: "Coordinate registration materials", copy: "We organise the name, office, partner details and supporting information into a consistent filing workstream.", bullets: ["Review name options and the registered-office arrangement", "Coordinate consents, declarations and identity information", "Prepare incorporation documents before submission"] },
    { title: "Make the LLP usable from day one", copy: "After registration, the focus turns to the agreement, records and calendar that support the partnership.", bullets: ["Complete the LLP agreement and associated filing work", "Set up contribution and partner records with supporting approvals", "Map annual and event-based work against the LLP's activity"] },
  ] },
  "one-person-company": { intro: "An OPC offers a focused company route for an individual founder, but the nominee, governance and early compliance work still need careful attention from the start.", sections: [
    { title: "Confirm the proposed route", copy: "We begin by assessing the founder's plans against the intended company structure.", bullets: ["Discuss the founder's role, business plan and expected growth", "Consider the nominee arrangement and how it will be kept current", "Identify whether another company form may better suit future ownership changes"] },
    { title: "Document founder and nominee roles", copy: "The incorporation record should make the key people and responsibilities clear.", bullets: ["Coordinate founder, director and nominee details and consents", "Prepare constitutional documents around the planned activity", "Review name and registered-office inputs before filing"] },
    { title: "Organise the filing journey", copy: "A focused checklist helps keep each input, approval and supporting document visible.", bullets: ["Create a checklist for information and approvals", "Prepare incorporation documents and coordinate submission", "Keep the certificate and core company documents organised"] },
    { title: "Plan for the first year", copy: "A sole founder still needs reliable records and a practical company rhythm.", bullets: ["Set up statutory registers, share records and initial resolutions", "Identify immediate operational registrations and banking actions", "Keep nominee, governance and annual reviews on a clear calendar"] },
  ] },
  "section-8-company": { intro: "A Section 8 company begins with its purpose. Its objects, proposed activities and governance arrangements need to show a coherent not-for-profit model before incorporation materials are prepared.", sections: [
    { title: "Define the purpose carefully", copy: "We translate the organisation's public-benefit work into a clear starting framework.", bullets: ["Clarify charitable or not-for-profit objects and activities", "Identify intended members, directors and governance roles", "Consider the funding model and use of income"] },
    { title: "Build the incorporation record", copy: "Objects, constitutional documents and application materials should tell one consistent story.", bullets: ["Prepare documents around the purpose and governance model", "Coordinate declarations, consents and supporting information", "Review name and registered-office inputs"] },
    { title: "Establish practical governance", copy: "Purpose-led work benefits from clear decision records and controls over funds and activities.", bullets: ["Set out board and member roles and approval routes", "Prepare initial resolutions and statutory records", "Identify policies suited to planned programmes and funding"] },
    { title: "Map the first compliance horizon", copy: "Company-law work sits alongside any tax, fundraising, sectoral or operational requirements that apply.", bullets: ["Create a calendar for records, meetings and annual actions", "Review whether separate registrations are relevant to activities", "Keep changes in objects, directors, members or office under review"] },
  ] },
  "foreign-subsidiary": { intro: "Establishing an Indian subsidiary calls for the company-incorporation process and foreign-investment analysis to move together. The appropriate route depends on the proposed activity, ownership, funding path and parent group's India-entry plan.", sections: [
    { title: "Scope the India entry", copy: "The first step is understanding what the Indian entity will do and how it will sit within the group.", bullets: ["Map activities, ownership chain and Indian management arrangements", "Review proposed capitalisation and early operating needs", "Identify company-law, sectoral, tax or foreign-investment questions"] },
    { title: "Align incorporation and investment", copy: "The company's constitutional documents should work alongside the contemplated investment and group structure.", bullets: ["Coordinate the proposed name, objects, office and directors", "Prepare incorporation materials with investment documents in view", "Organise parent-company approvals and signatory records"] },
    { title: "Coordinate funding and reporting", copy: "Foreign investment work should be planned against transaction documents and the banking process, not treated as an afterthought.", bullets: ["Review the investment route and applicable conditions before execution", "Coordinate documents with the authorised dealer bank and stakeholders", "Keep issue, allotment and reporting actions connected to records"] },
    { title: "Set up a reliable Indian record", copy: "After incorporation, the subsidiary needs an orderly corporate file and an appropriate compliance calendar.", bullets: ["Set up registers, share records, approvals and group-authority records", "Map company filings, foreign-investment reporting and annual reviews as applicable", "Review ownership, director, address and capital changes before they take effect"] },
  ] },
};

export function generateStaticParams() { return Object.keys(practiceAreas).map((slug) => ({ slug })); }

export default function PracticeAreaPage({ params }: { params: { slug: string } }) {
  if (params.slug === "section-8-company-foreign-subsidiary") redirect("/practice-areas/section-8-company");
  const area = practiceAreas[params.slug as keyof typeof practiceAreas];
  if (!area) notFound();
  const complianceGuide = complianceGuides[params.slug];
  const engagement = "engagement" in area ? area.engagement : null;

  return <main className="practice-area-page">
    <SiteHeader />
    <section className="hero practice-hero">
      <div className="hero-slides" aria-hidden="true"><div className="hero-slide is-active" style={{ backgroundImage: "url('/images/sattva/practice-areas-hero.jpg')" }} /></div>
      <div className="hero-shade" />
      <div className="hero-content shell"><div className="hero-copy-set practice-hero-copy"><p className="eyebrow light"><em>{area.eyebrow}</em> <i /> Sattva Law &amp; Associates</p><h1 className={heroTitleClass(area.title)}>{area.title}</h1><div className="hero-actions"><a className="button button-light" href="#scope">Explore the scope <ArrowDownRight size={17} /></a></div></div></div>
      <div className="hero-rail">BUSINESS LAW &middot; REGULATORY PRACTICE &middot; CORPORATE GOVERNANCE</div>
    </section>
    <section className="detail-intro shell" id="scope"><header className="detail-heading"><p className="eyebrow">{area.eyebrow}</p><h2>{area.focusTitle}<br /><em>{area.focusEmphasis}</em></h2><p>{area.lead}</p></header><div className="detail-intro-grid"><figure className="detail-intro-image"><img src={area.image} alt={area.imageAlt} /><figcaption>Practical legal guidance for the work ahead.</figcaption></figure><div className="detail-intro-copy"><p className="eyebrow">THE APPROACH</p>{area.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>
    <section className="detail-cards"><div className="shell"><header className="detail-heading"><p className="eyebrow">IN THIS AREA</p><h2>Support built around<br /><em>the next decision.</em></h2><p>Each engagement is shaped to the facts, documents and action in front of you.</p></header><div className="detail-card-grid">{area.scope.map((item, index) => { const Icon = detailIcons[index % detailIcons.length]; return <article key={item}><div className="detail-card-top"><span>{String(index + 1).padStart(2, "0")}</span><i><Icon size={27} strokeWidth={1.35} /></i></div><h3>{item}</h3><ArrowDownRight size={19} aria-hidden="true" /></article>; })}</div></div></section>
    <section className="detail-process shell"><div className="detail-process-copy"><p className="eyebrow">WORKING APPROACH</p><h2>A measured route,<br /><em>made clear.</em></h2><p>A considered sequence from the first question to the action that follows.</p><ol>{area.workflow.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol></div><figure className="detail-process-image"><img src={area.image} alt={area.imageAlt} /><figcaption>Clear structure for the work ahead.</figcaption></figure></section>
    <section className="detail-ready"><div className="shell"><header className="detail-heading"><p className="eyebrow">COMPLIANCE IN PRACTICE</p><h2>What follows the<br /><em>first step.</em></h2></header><div><p>{complianceGuide.intro}</p><ul>{(engagement ? [...engagement.start, ...engagement.delivery] : complianceGuide.items.map((item) => item.title)).map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></div></div></section>
    <section className="detail-cta"><div className="shell"><p className="eyebrow">NEXT STEP</p><h2><span>Let&apos;s discuss the</span><em>right way forward.</em></h2><p>Share a brief outline of your requirement. We will respond with an appropriate next step.</p><a className="detail-cta-button" href="mailto:sattvalawandassociates@gmail.com">Start an enquiry <ArrowDownRight size={17} /></a></div></section>
    <SiteFooter />
  </main>;
}
