export const servicePages = [
  {
    slug: "business-formation",
    label: "Business formation",
    title: "Business formation & structuring",
    eyebrow: "Capabilities",
    intro: "Thoughtful support at the point your enterprise takes shape.",
    detail: "Choosing the appropriate structure at the outset helps create a practical foundation for the work ahead. We assist with the registration process and the supporting steps needed to get a business established.",
    overview: ["The first legal decisions shape how a business can operate, grow and bring people into the venture. We help founders work through the available structures and the practical points that should be settled before an application is made.", "Once the preferred route is clear, we coordinate the core documentation and filing steps in a simple sequence, while keeping the initial compliance responsibilities visible."],
    items: ["Private limited company registration", "Limited liability partnership registration", "One person company registration", "Section 8 company registration", "Foreign subsidiary incorporation"],
    steps: ["Understand the business model and ownership plan", "Choose the appropriate legal structure", "Prepare the incorporation documents and application", "Set out the first records and compliance actions"],
    prepare: ["Proposed business and company details", "Founder, director or partner information", "Registered-office details", "A clear view of ownership and management roles"],
  },
  {
    slug: "registrations-licences",
    label: "Registrations & licences",
    title: "Registrations & operating licences",
    eyebrow: "Capabilities",
    intro: "Practical help navigating registrations needed for operations.",
    detail: "Operating requirements vary by business and location. We help identify the registrations relevant to the activity in question and support the application and documentation process.",
    overview: ["Registrations and licences are easier to manage when they are considered as part of the way a business will actually operate. We begin by understanding the activity, location and immediate operational plans.", "We then help organise the relevant applications and supporting information, so that the next actions are clear rather than fragmented across several processes."],
    items: ["IEC and MSME (Udyam) registration", "Startup India registration", "Shop and Establishment licence", "12A and 80G registration"],
    steps: ["Review the activity and operating location", "Identify the registrations that may apply", "Prepare the application information", "Submit, track and organise the resulting records"],
    prepare: ["Entity and business details", "Registered-office or operating-address documents", "Authorised-person details", "A short description of the proposed activity"],
  },
  {
    slug: "annual-compliance",
    label: "Annual compliance",
    title: "Annual and ongoing compliance",
    eyebrow: "Capabilities",
    intro: "A reliable rhythm for essential statutory responsibilities.",
    detail: "Regular filings and company records need a clear process. We help businesses organise ongoing statutory work so due dates, records and annual requirements remain visible and manageable.",
    overview: ["Ongoing compliance works best as a routine rather than a last-minute exercise. We help clients create a practical calendar around their entity type, activity and reporting obligations.", "The work is organised around the documents, approvals and deadlines that recur through the year, giving the business a clearer view of what needs attention and when."],
    items: ["GST registration", "Annual ROC and LLP filings", "DIR-3 KYC filing", "Ongoing company compliance support"],
    steps: ["Review the entity's current position", "Map recurring and event-based obligations", "Prepare records and filings to a clear timetable", "Maintain a visible compliance calendar"],
    prepare: ["Previous filing and incorporation records", "Recent financial and transaction information", "Director or designated-partner details", "A list of changes since the last reporting period"],
  },
  {
    slug: "contracts-documentation",
    label: "Contracts",
    title: "Contracts & legal documentation",
    eyebrow: "Capabilities",
    intro: "Clear paperwork that reflects the understanding behind a deal.",
    detail: "Well-considered documentation can make commercial relationships easier to navigate. We prepare and review practical agreements that set out the terms, responsibilities and expectations involved.",
    overview: ["Good documentation starts with the commercial arrangement, not a generic form. We take time to understand who is doing what, what is being exchanged and where the practical risks sit.", "That helps us prepare or review documents that are clearer to use in day-to-day work and better aligned with the intended relationship."],
    items: ["Founder and shareholder agreements", "Employment and vendor agreements", "Partnership and franchise agreements", "Non-disclosure and lease documentation"],
    steps: ["Understand the commercial arrangement", "Identify the key responsibilities and protections", "Draft or review the proposed terms", "Support a clear execution and record-keeping process"],
    prepare: ["A summary of the intended arrangement", "Names and roles of the parties", "Existing term sheets, emails or draft documents", "Key commercial dates, deliverables and payment terms"],
  },
  {
    slug: "sebi-compliance",
    label: "SEBI compliance",
    title: "SEBI registration & compliance setup",
    eyebrow: "Capabilities",
    intro: "Process-led assistance for regulated investment professionals.",
    detail: "For research analysts and investment advisers, registration is only one part of the work. We support the documents, operating controls and review routines that help a regulated practice begin in an orderly way.",
    overview: ["The work starts with a focused review of the proposed activity, applicant structure, client journey and public-facing communications. This helps identify the registration route, information gaps and the operating controls that should be designed before launch.", "We then coordinate the application materials and supporting information in a clear sequence. The aim is to create a consistent record across the application, policies, disclosures and the way the practice will actually operate.", "Beyond registration, we help turn the framework into a practical compliance setup: accountable owners, document controls, client-facing materials, registers and a calendar for regular review. The final scope is tailored to the activity and current requirements."],
    items: ["Research analyst registration-readiness support", "Investment adviser registration-readiness support", "Client, disclosure and communication documentation", "One-time compliance setup and policy framework", "RA and IA audit-readiness planning"],
    steps: ["Map the proposed regulated activity and client journey", "Review readiness, documents and responsibilities", "Prepare the application and operating materials", "Set up the policies, records and compliance calendar"],
    prepare: ["Business, ownership and registered-office details", "Relevant qualification, experience and personnel information", "Existing policies, disclosures, agreements and public materials", "A clear outline of the proposed activity and client-facing process", "Internal contacts who will own approvals and ongoing records"],
  },
  {
    slug: "audit-readiness",
    label: "Audit readiness",
    title: "Audit readiness & regulatory filings",
    eyebrow: "Capabilities",
    intro: "Measured preparation for regulatory reviews and ongoing filing obligations.",
    detail: "A clear audit trail and reliable filing process can reduce uncertainty around regulated work. We help organise records, test key compliance materials and coordinate the filing steps that need careful follow-through.",
    overview: ["Audit readiness is not a last-minute document collection exercise. It begins with understanding how the practice actually operates, where decisions are recorded and whether the evidence behind each control can be located and explained.", "We work through the relevant policies, registers, client materials, reports, approvals and prior filings to identify gaps in a practical order. The outcome is a focused action list rather than a generic compliance checklist.", "Where a filing or response is required, we coordinate the supporting documents, review points and timetable so that the submission and its retained records remain connected."],
    items: ["RA and IA audit-readiness review", "Compliance process and document-control review", "Records, registers and evidence-trail organisation", "FCGPR and FCTRS filing support", "Coordination with authorised dealer banks"],
    steps: ["Understand the operating model, review scope and timeline", "Review records, prior filings and key compliance materials", "Prioritise gaps and prepare supporting documents", "Coordinate submission, follow-up and record retention"],
    prepare: ["Past filings, correspondence and any review observations", "Relevant policies, registers, client materials and supporting records", "Research reports, advisory records or transaction documents as applicable", "Internal contacts responsible for approvals, operations and information", "A realistic timeline for the review, filing or response"],
  },
  {
    slug: "strategic-support",
    label: "Strategic support",
    title: "Board, funding & strategic support",
    eyebrow: "Capabilities",
    intro: "A considered legal perspective when your business is moving forward.",
    detail: "Some business decisions need legal work that extends beyond one form or filing. We provide focused support around funding, reporting, board processes and the documentation that accompanies change.",
    overview: ["Periods of change often involve several connected legal actions: a board decision, a transaction document, a filing and a new set of records. We help clients see the full sequence rather than treating each item in isolation.", "The support is designed to give founders and management a clearer route through funding, governance and cross-border reporting work as the business moves forward."],
    items: ["FEMA reporting: FCGPR and FCTRS", "Funding-readiness guidance", "Board meeting assistance", "Company conversions and secretarial work"],
    steps: ["Understand the proposed decision or transaction", "Map approvals, documentation and reporting points", "Prepare the relevant records and filings", "Support the next governance or compliance action"],
    prepare: ["A summary of the proposed change or transaction", "Current corporate and ownership records", "Draft commercial terms or board materials", "Relevant banking, investor or counterparty information"],
  },
] as const;
